config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  devise_for :users
  resources :users
  resources :gears
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gear.rb
class Gear < ApplicationRecord
 belongs_to :user
 attachment :image

 with_options presence: true do
    validates :title
    validates :body
    validates :image
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :gears, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
    end


end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    @gears = Gear.all.order(id: "DESC")
  end

  def show
    @gear = Gear.find(params[:id])
  end

  def new
    @gear = Gear.new
  end
  

  def create
    @gear = current_user.gears.build(gear_params)
    @gear.user_id = current_user.id
    @gear.save
    redirect_to gear_path(@gear)
  end

  def edit
    @gear = Gear.find(params[:id])
  end

  def update
    @gear = Gear.find(params[:id])
    @gear.update(gear_params)
    redirect_to gear_path(@gear)
  end

  def destroy
    gear = Gear.find(params[:id])
    gear.destroy
    redirect_to gears_path
  end

  
  private
    def gear_params
       params.require(:gear).permit(:title, :body, :image, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gears = Gear.all.order(id: "DESC")
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gears/edit.html.erb
<%= form_for @gear do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>

app/views/gears/index.html.erb
<h1 class="sectiontitle">新着投稿</h1>

<div class="gearpage">
    <% @gears.each do |gear| %>

        <div class="post">
            <div>
            <%= link_to gear_path(gear) do %> <%=  attachment_image_tag gear, :image ,class: "gearthumb"  %> <% end %>
            </div>

            <div class="geardetail">
                <%= link_to gear.title ,gear_path(gear),class: "geartitle" %>
                <br>
                <%= truncate(gear.body , length: 32) %>
            </div>

        </div>
    <% end %>
</div>

app/views/gears/new.html.erb
<h1 class="sectiontitle">新規投稿</h1>

<%= form_for @gear do |f| %>
          <div class="field">
            <%= f.label :title, "ブランド・機種名" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真" %>
            <%= f.file_field :image %>
          </div>

          <%= f.submit '投稿する', class: "button" %>
        <% end %>

app/views/gears/show.html.erb
<h1 class="sectiontitle"><%= @gear.title %></h1>


<div class="gearpage">
          <div>
              <%=  attachment_image_tag @gear, :image ,class: "gearimage"  %>
          </div>



              

          <div class="gearsentence">
                <%= simple_format @gear.body %>


                <p class="ownername">
                  投稿者<br>
                  <%= link_to user_path(@gear.user) do %><%= @gear.user.username %>さん
                <% end %>
                </p>

                <%= attachment_image_tag @gear.user, :profile_image, fallback: "no-image.png", class: "userthumb" %><br>
                <p class="text-center">
                <%= @gear.user.profile %>
                </p>

          </div>
</div>

app/views/home/index.html.erb
            <% if user_signed_in? %>
<h1 class="sectiontitle">ようこそ、<%= current_user.username %>さん</h1>

<h1 class="sectiontitle">新着機材</h1>
<div class="gearpage">
    <% @gears.each do |gear| %>

        <div class="post">
            <div>
            <%= link_to gear_path(gear) do %> <%=  attachment_image_tag gear, :image ,class: "gearthumb"  %> <% end %>
            </div>

            <div class="geardetail">
                <%= link_to gear.title ,gear_path(gear),class: "geartitle" %>
                <br>
                <%= truncate(gear.body , length: 32) %>
            </div>
        </div>
    <% end %>
    <%= link_to "すべての投稿一覧はこちら", gears_path, class: "nav-link" %>

</div>



            <% else %>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading"></div>
                <div class="masthead-heading text-uppercase">find your new gear</div>
                <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary btn-xl text-uppercase" %><br><br><br>
                <p>または：<%= link_to "アカウントをお持ちですか？", new_user_session_path, class: "alreadySigned" %></p>
            </div>
        </header>

        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Services</h2>
                    <p class="text-muted">
                    こんなお悩みはありませんか？<br>
                    『欲しいペダルの流通が無く、置いてある楽器店が無い・・・』<br>
                    『楽器店で試した時は良かったが、自分のアンプとの相性が合わなかった・・・』<br>
                    『手の届かないあのヴィンテージ・ペダル、一度でいいから鳴らしてみたい！』<br>
                    MY NEW PEERがお悩みを解決します。あなたはもう、賭けに出るような気持ちでペダルを買わなくていいのです！
                    </p>
                </div>
                <div class="row text-center">
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-tablet fa-stack-1x fa-inverse"></i>
                        </span>
                        <h4 class="my-3">Try'em all!</h4>
                        <p class="text-muted">あなたが次に買おうと思っていたあのペダル、他の誰かが持っているかも？お持ちの楽器と組み合わせて、試させてもらいましょう！</p>
                    </div>
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-user-friends fa-stack-1x fa-inverse"></i>
                        </span>
                        <h4 class="my-3">Seek a geek</h4>
                        <p class="text-muted">気の合うプレイヤーや、頼れるエフェクター・フリークと知り合えるかもしれません！あなたの音楽人生に大きな影響をもたらす人と出会えるかも？</p>
                    </div>
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
                        </span>
                        <h4 class="my-3">Trading</h4>
                        <p class="text-muted">試したペダルを気に入って、持ち主も売却可能ならその場で購入しましょう。支払い方法は現金でも、ペダル同士の交換でもOK。</p>
                    </div>

                </div>
            </div>
        </section>


        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">はじめよう</h2><br>
                    <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary btn-xl text-uppercase" %><br><br>
                    <%= link_to "アカウントをお持ちですか？", new_user_session_path, class: "alreadySigned" %>
                </div>




            </div>
        </section>
        
        <% end %>

app/views/layouts/BUapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipegram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Notable&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  </head>

  <body>

  

      <header class="sticky-top">
      <nav class="navbar navbar-expand-md navbar-dark">
          <%= link_to root_path do %>
            <h1 class="title" style="font-family: Notable; ">My New Peer</h1>
            <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "新着投稿", gears_path, class: "button" %>
              </li>

              <li class="nav-item">
              <%= link_to "MY PAGE", user_path(current_user), class: "button" %>
              </li>
              <li class="nav-item">
              <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "button" %>
              </li>

              
            <% else %>
              <li class="nav-item">
              <%= link_to "SIGN UP", new_user_registration_path, class: "button" %>
              </li>
              <li class="nav-item">
              <%= link_to "LOG IN", new_user_session_path, class: "button" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>










  <div class="bgimage">
        <div class="container">
          <% if flash[:notice] %>
            <div class="notification is-info">
              <p class="notice"><%= notice %></p>
            </div>
          <% end %>

          <% if flash[:alert] %>
            <div class="notification is-danger">
              <p class="alert"><%= alert %></p>
            </div>
          <% end %>
          </div>




      <section class="main firstbgcolor">
        <div class="container">
          <%= yield %>
          </div>
      </section>

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>



</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MY NEW PEER</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    </head>
    <body id="page-top">
    <div class="bodyTopPad"></div>
            <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-shrink" id="mainNav">
            <div class="container">
                <%= link_to "MY NEW PEER", root_path, class: "navbar-brand" %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "新着投稿", gears_path, class: "nav-link" %>
              </li>

              <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>

              
            <% else %>
              <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
                    </ul>
                </div>
            </div>
        </nav>


        <%= yield %>


        <!-- Footer-->
        <footer class="footer py-4">
            <div class="align-items-center">
                <p>Copyright &copy; MY NEW PEER 2023</p>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.file_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="">

      <h1 class="title">
        Users
      </h1>

</section>

<section class="section">

    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

</section>

app/views/users/show.html.erb
<h1 class="sectiontitle"><%= @user.username %>さんのユーザー詳細</h1>

<div class="profile">
    <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image" %><br>
    <div class="profilesentence">
      <%= @user.profile %>
    </div>
    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
</div>

<p class="sectiontitle">掲載中の機材</p>
<div class="gearpage">
    <% @user.gears.each do |gear| %>
        <div class="post">
            <div>
                <%=  attachment_image_tag gear, :image ,class: "gearthumb"  %>
            </div>

            <div class="geardetail">
                <%= link_to gear.title ,gear_path(gear),class: "geartitle"  %><br>
                <%= link_to "詳細", gear_path(gear) %>
                <%= link_to "編集", edit_gear_path(gear) %>
                <%= button_to '削除', gear_path(gear),  method: :delete, form: { data: { turbo_confirm: "本当に削除しますか？", turbo_frame: '_top' } },class: "deletelink"  %>
            </div>

        </div>
    <% end %>
</div>